configured_endpoints: 9
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/moon-banking%2Fmoon-banking-9fde22381c127db4afbf4b10a0b90e666bdb7bae4ae6fa18a0820ada8d2ba347.yml
openapi_spec_hash: df05630ec15933a3ca0761cb6740cb8d
config_hash: 55b5b7b39b8dbc4c37ca3cd9de08a899
