configured_endpoints: 11
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/moon-banking/moon-banking-7e56cb4d71d25b18347ac5cfd352be6fc535ad827088cc6a449826e4fe43118f.yml
openapi_spec_hash: e57f11cf4a2ca43c37afbb88afbc30cc
config_hash: 4b4a3cddecc8c9d30e70d882cfde7a48
